name: 'Check all commits'
description: 'no description'
inputs:
  git_token:
    description: 'token for access in private repos'
    requred: true
outputs:
  result: 
    description: "Result dict"
    value: ${{ steps.python.outputs.result }}
runs:
  using: "composite"
  steps: 
    - name: Get json
      shell: bash
      run: |
        curl -u "${{ github.actor }}:${{ inputs.git_token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/jnqa/ttest/commits > commits.json
    - name: Python
      id: python
      shell: python3
      run: |
        import json
        import sys
        report = ""
        with open('test.json', 'r', encoding='utf-8') as t:
            all_commits = json.load(t)
        for i in all_commits:
            # report.append({'name':i['commit']['author']['name'],'message':i['commit']['message']})
            report=f"{report}{i['commit']['author']['name']}:{i['commit']['message']}\n"
            # print(f"{i['commit']['author']['name']}: {i['commit']['message']}")
        print(report)