name: 'Check all commits'
description: 'no description'
inputs:
  git_token:
    description: 'token for access in private repos'
    requred: true
outputs:
  result: 
    description: "Result dict"
    value: ${{ steps.python.outputs.result }}
runs:
  using: "composite"
  steps: 
    - name: Get json
      shell: bash
      run: |
        curl -u "${{ github.actor }}:${{ inputs.git_token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/jnqa/ttest/commits > commits.json
        python3 reformat.py