name: 'Check all commits'
description: 'no description'
inputs:
  git_actor:
    required: true
  git_token:
    description: 'token for access in private repos'
    requred: true
  repos:
    description: 'repos to read'
    requred: true
outputs:
  result: 
    description: "Result dict"
    value: ${{ steps.python.outputs.result }}
runs:
  using: "composite"
  steps: 
    - name: Get json
      shell: bash
      run: |
        git log --pretty=oneline v0.0.1..v0.0.2
        # echo "actor:${{ inputs.actor }}"
        # echo "repos:repos/${{ inputs.repos }}/commits"
        # curl -u "${{ inputs.actor }}:${{ inputs.git_token }}" \
        #   -H "Accept: application/vnd.github.v3+json" \
        #   https://api.github.com/repos/${{ inputs.repos }}/commits > commits.json
        # which jq || sudo apt install jq -y
        # cat commits.json | jq .[0] || echo bad