name: 'Check all commits'
description: 'no description'
inputs:
  git_token:
    description: 'token for access in private repos'
    requred: true
outputs:
  result: 
    description: "Result dict"
    value: ${{ steps.python.outputs.result }}
runs:
  using: "composite"
  steps: 
    - name: Get json
      shell: bash
      run: |
        curl -u "${{ github.actor }}:${{ inputs.git_token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/jnqa/ttest/commits > commits.json
        cat << EOF > /tmp/reformat.py
        These contents will be written to the file.
        import json
        import sys
        report = ""
        with open('test.json', 'r', encoding='utf-8') as t:
            all_commits = json.load(t)
        for i in all_commits:
            report=f"{report}{i['commit']['author']['name']}:{i['commit']['message']}\n"
        print(report)
        EOF
        python3 /tmp/reformat.py